apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "logstash.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
